
from PyQt5 import QtCore, QtGui, QtWidgets


class keyboardWindow(QtWidgets.QDialog):
    
    textToReturn = QtCore.pyqtSignal(str)
    
    def __init__(self):
        super().__init__()
		
        self.title = "Keyboard"
        self.left = 500
        self.top = 200
        self.width = 50
        self.height = 30
        self.iconName = "mouseicon.png"
        
        self.initWindow()
        
        self.UpperCaseLetters()
        
    def initWindow(self):
        self.setWindowTitle(self.title)
        self.setWindowIcon(QtGui.QIcon(self.iconName))
        #self.setGeometry(self.left, self.top, self.width, self.height)
        
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        
        self.lineEdit = QtWidgets.QLineEdit()
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 0, 1, 12)
        
        self.C_pushButton = QtWidgets.QPushButton()
        self.C_pushButton.setObjectName("C_pushButton")
        self.C_pushButton.clicked.connect(self.Writer)
        sizePolicy.setHeightForWidth(self.C_pushButton.sizePolicy().hasHeightForWidth())
        self.C_pushButton.setSizePolicy(sizePolicy)
        self.gridLayout.addWidget(self.C_pushButton, 4, 8, 1, 1)
        
        self.Exclamation_pushButton = QtWidgets.QPushButton()
        self.Exclamation_pushButton.setObjectName("Exclamation_pushButton")
        self.Exclamation_pushButton.clicked.connect(self.Writer)
        sizePolicy.setHeightForWidth(self.Exclamation_pushButton.sizePolicy().hasHeightForWidth())
        self.Exclamation_pushButton.setSizePolicy(sizePolicy)
        self.gridLayout.addWidget(self.Exclamation_pushButton, 1, 10, 1, 1)
        
        self.YpushButton = QtWidgets.QPushButton()
        self.YpushButton.setObjectName("YpushButton")
        self.YpushButton.clicked.connect(self.Writer)
        sizePolicy.setHeightForWidth(self.YpushButton.sizePolicy().hasHeightForWidth())
        self.YpushButton.setSizePolicy(sizePolicy)
        self.gridLayout.addWidget(self.YpushButton, 2, 5, 1, 1)
        
        self.BpushButton = QtWidgets.QPushButton()
        self.BpushButton.setObjectName("BpushButton")
        self.BpushButton.clicked.connect(self.Writer)
        sizePolicy.setHeightForWidth(self.BpushButton.sizePolicy().hasHeightForWidth())
        self.BpushButton.setSizePolicy(sizePolicy)
        self.gridLayout.addWidget(self.BpushButton, 4, 4, 1, 1)
        
        self.SubDash_pushButton = QtWidgets.QPushButton()
        self.SubDash_pushButton.setObjectName("SubDash_pushButton")
        self.SubDash_pushButton.clicked.connect(self.Writer)
        sizePolicy.setHeightForWidth(self.SubDash_pushButton.sizePolicy().hasHeightForWidth())
        self.SubDash_pushButton.setSizePolicy(sizePolicy)
        self.gridLayout.addWidget(self.SubDash_pushButton, 4, 11, 1, 1)
        
        self.EightpushButton = QtWidgets.QPushButton()
        self.EightpushButton.setObjectName("EightpushButton")
        self.EightpushButton.clicked.connect(self.Writer)
        sizePolicy.setHeightForWidth(self.EightpushButton.sizePolicy().hasHeightForWidth())
        self.EightpushButton.setSizePolicy(sizePolicy)
        self.gridLayout.addWidget(self.EightpushButton, 1, 7, 1, 1)
        
        self.EpushButton = QtWidgets.QPushButton()
        self.EpushButton.setObjectName("EpushButton")
        self.EpushButton.clicked.connect(self.Writer)
        sizePolicy.setHeightForWidth(self.EpushButton.sizePolicy().hasHeightForWidth())
        self.EpushButton.setSizePolicy(sizePolicy)
        self.gridLayout.addWidget(self.EpushButton, 2, 2, 1, 1)
        
        self.Dot_pushButton = QtWidgets.QPushButton()
        self.Dot_pushButton.setObjectName("Dot_pushButton")
        self.Dot_pushButton.clicked.connect(self.Writer)
        sizePolicy.setHeightForWidth(self.Dot_pushButton.sizePolicy().hasHeightForWidth())
        self.Dot_pushButton.setSizePolicy(sizePolicy)
        self.gridLayout.addWidget(self.Dot_pushButton, 4, 9, 1, 1)
        
        self.OnepushButton = QtWidgets.QPushButton()
        self.OnepushButton.setObjectName("OnepushButton")
        self.OnepushButton.clicked.connect(self.Writer)
        sizePolicy.setHeightForWidth(self.OnepushButton.sizePolicy().hasHeightForWidth())
        self.OnepushButton.setSizePolicy(sizePolicy)
        self.gridLayout.addWidget(self.OnepushButton, 1, 0, 1, 1)
        
        self.TwopushButton = QtWidgets.QPushButton()
        self.TwopushButton.setObjectName("TwopushButton")
        self.TwopushButton.clicked.connect(self.Writer)
        sizePolicy.setHeightForWidth(self.TwopushButton.sizePolicy().hasHeightForWidth())
        self.TwopushButton.setSizePolicy(sizePolicy)
        self.gridLayout.addWidget(self.TwopushButton, 1, 1, 1, 1)
        
        self.CpushButton = QtWidgets.QPushButton()
        self.CpushButton.setObjectName("CpushButton")
        self.CpushButton.clicked.connect(self.Writer)
        sizePolicy.setHeightForWidth(self.CpushButton.sizePolicy().hasHeightForWidth())
        self.CpushButton.setSizePolicy(sizePolicy)
        self.gridLayout.addWidget(self.CpushButton, 4, 2, 1, 1)
        
        self.S_pushButton = QtWidgets.QPushButton()
        self.S_pushButton.setObjectName("S_pushButton")
        self.S_pushButton.clicked.connect(self.Writer)
        sizePolicy.setHeightForWidth(self.S_pushButton.sizePolicy().hasHeightForWidth())
        self.S_pushButton.setSizePolicy(sizePolicy)
        self.gridLayout.addWidget(self.S_pushButton, 3, 9, 1, 1)
        
        self.NinepushButton = QtWidgets.QPushButton()
        self.NinepushButton.setObjectName("NinepushButton")
        self.NinepushButton.clicked.connect(self.Writer)
        sizePolicy.setHeightForWidth(self.NinepushButton.sizePolicy().hasHeightForWidth())
        self.NinepushButton.setSizePolicy(sizePolicy)
        self.gridLayout.addWidget(self.NinepushButton, 1, 8, 1, 1)
        
        self.RpushButton = QtWidgets.QPushButton()
        self.RpushButton.setObjectName("RpushButton")
        self.RpushButton.clicked.connect(self.Writer)
        sizePolicy.setHeightForWidth(self.RpushButton.sizePolicy().hasHeightForWidth())
        self.RpushButton.setSizePolicy(sizePolicy)
        self.gridLayout.addWidget(self.RpushButton, 2, 3, 1, 1)
        
        self.G_pushButton = QtWidgets.QPushButton()
        self.G_pushButton.setObjectName("G_pushButton")
        self.G_pushButton.clicked.connect(self.Writer)
        sizePolicy.setHeightForWidth(self.G_pushButton.sizePolicy().hasHeightForWidth())
        self.G_pushButton.setSizePolicy(sizePolicy)
        self.gridLayout.addWidget(self.G_pushButton, 2, 10, 1, 1)
        
        self.ZeropushButton = QtWidgets.QPushButton()
        self.ZeropushButton.setObjectName("ZeropushButton")
        self.ZeropushButton.clicked.connect(self.Writer)
        sizePolicy.setHeightForWidth(self.ZeropushButton.sizePolicy().hasHeightForWidth())
        self.ZeropushButton.setSizePolicy(sizePolicy)
        self.gridLayout.addWidget(self.ZeropushButton, 1, 9, 1, 1)
        
        self.XpushButton = QtWidgets.QPushButton()
        self.XpushButton.setObjectName("XpushButton")
        self.XpushButton.clicked.connect(self.Writer)
        sizePolicy.setHeightForWidth(self.XpushButton.sizePolicy().hasHeightForWidth())
        self.XpushButton.setSizePolicy(sizePolicy)
        self.gridLayout.addWidget(self.XpushButton, 4, 1, 1, 1)
        
        self.VpushButton = QtWidgets.QPushButton()
        self.VpushButton.setObjectName("VpushButton_2")
        self.VpushButton.clicked.connect(self.Writer)
        sizePolicy.setHeightForWidth(self.VpushButton.sizePolicy().hasHeightForWidth())
        self.VpushButton.setSizePolicy(sizePolicy)
        self.gridLayout.addWidget(self.VpushButton, 4, 3, 1, 1)
        
        self.I_pushButton = QtWidgets.QPushButton()
        self.I_pushButton.setObjectName("I_pushButton")
        self.I_pushButton.clicked.connect(self.Writer)
        sizePolicy.setHeightForWidth(self.I_pushButton.sizePolicy().hasHeightForWidth())
        self.I_pushButton.setSizePolicy(sizePolicy)
        self.gridLayout.addWidget(self.I_pushButton, 3, 10, 1, 1)
        
        self.OpushButton = QtWidgets.QPushButton()
        self.OpushButton.setObjectName("OpushButton")
        self.OpushButton.clicked.connect(self.Writer)
        sizePolicy.setHeightForWidth(self.OpushButton.sizePolicy().hasHeightForWidth())
        self.OpushButton.setSizePolicy(sizePolicy)
        self.gridLayout.addWidget(self.OpushButton, 2, 8, 1, 1)
        
        self.MpushButton = QtWidgets.QPushButton()
        self.MpushButton.setObjectName("MpushButton")
        self.MpushButton.clicked.connect(self.Writer)
        sizePolicy.setHeightForWidth(self.MpushButton.sizePolicy().hasHeightForWidth())
        self.MpushButton.setSizePolicy(sizePolicy)
        self.gridLayout.addWidget(self.MpushButton, 4, 6, 1, 1)
        
        self.KpushButton = QtWidgets.QPushButton()
        self.KpushButton.setObjectName("KpushButton")
        self.KpushButton.clicked.connect(self.Writer)
        sizePolicy.setHeightForWidth(self.KpushButton.sizePolicy().hasHeightForWidth())
        self.KpushButton.setSizePolicy(sizePolicy)
        self.gridLayout.addWidget(self.KpushButton, 3, 7, 1, 1)
        
        self.ThreepushButton = QtWidgets.QPushButton()
        self.ThreepushButton.setObjectName("ThreepushButton")
        self.ThreepushButton.clicked.connect(self.Writer)
        sizePolicy.setHeightForWidth(self.ThreepushButton.sizePolicy().hasHeightForWidth())
        self.ThreepushButton.setSizePolicy(sizePolicy)
        self.gridLayout.addWidget(self.ThreepushButton, 1, 2, 1, 1)
        
        self.LpushButton = QtWidgets.QPushButton()
        self.LpushButton.setObjectName("LpushButton")
        self.LpushButton.clicked.connect(self.Writer)
        sizePolicy.setHeightForWidth(self.LpushButton.sizePolicy().hasHeightForWidth())
        self.LpushButton.setSizePolicy(sizePolicy)
        self.gridLayout.addWidget(self.LpushButton, 3, 8, 1, 1)
        
        self.Comma_pushButton = QtWidgets.QPushButton()
        self.Comma_pushButton.setObjectName("Comma_pushButton")
        self.Comma_pushButton.clicked.connect(self.Writer)
        sizePolicy.setHeightForWidth(self.Comma_pushButton.sizePolicy().hasHeightForWidth())
        self.Comma_pushButton.setSizePolicy(sizePolicy)
        self.gridLayout.addWidget(self.Comma_pushButton, 4, 10, 1, 1)
        
        self.WpushButton = QtWidgets.QPushButton()
        self.WpushButton.setObjectName("WpushButton")
        self.WpushButton.clicked.connect(self.Writer)
        sizePolicy.setHeightForWidth(self.WpushButton.sizePolicy().hasHeightForWidth())
        self.WpushButton.setSizePolicy(sizePolicy)
        self.gridLayout.addWidget(self.WpushButton, 2, 1, 1, 1)
        
        self.PpushButton = QtWidgets.QPushButton()
        self.PpushButton.setObjectName("PpushButton")
        self.PpushButton.clicked.connect(self.Writer)
        sizePolicy.setHeightForWidth(self.PpushButton.sizePolicy().hasHeightForWidth())
        self.PpushButton.setSizePolicy(sizePolicy)
        self.gridLayout.addWidget(self.PpushButton, 2, 9, 1, 1)
        
        self.FpushButton = QtWidgets.QPushButton()
        self.FpushButton.setObjectName("FpushButton")
        self.FpushButton.clicked.connect(self.Writer)
        sizePolicy.setHeightForWidth(self.FpushButton.sizePolicy().hasHeightForWidth())
        self.FpushButton.setSizePolicy(sizePolicy)
        self.gridLayout.addWidget(self.FpushButton, 3, 3, 1, 1)
        
        self.ApushButton = QtWidgets.QPushButton()
        self.ApushButton.setObjectName("ApushButton")
        self.ApushButton.clicked.connect(self.Writer)
        sizePolicy.setHeightForWidth(self.ApushButton.sizePolicy().hasHeightForWidth())
        self.ApushButton.setSizePolicy(sizePolicy)
        self.gridLayout.addWidget(self.ApushButton, 3, 0, 1, 1)
        
        self.Space_pushButton = QtWidgets.QPushButton()
        self.Space_pushButton.setObjectName("Space_pushButton")
        self.Space_pushButton.clicked.connect(self.Writer)
        sizePolicy.setHeightForWidth(self.Space_pushButton.sizePolicy().hasHeightForWidth())
        self.Space_pushButton.setSizePolicy(sizePolicy)
        self.gridLayout.addWidget(self.Space_pushButton, 1, 11, 1, 1)
        
        self.NpushButton = QtWidgets.QPushButton()
        self.NpushButton.setObjectName("NpushButton")
        self.NpushButton.clicked.connect(self.Writer)
        sizePolicy.setHeightForWidth(self.NpushButton.sizePolicy().hasHeightForWidth())
        self.NpushButton.setSizePolicy(sizePolicy)
        self.gridLayout.addWidget(self.NpushButton, 4, 5, 1, 1)
        
        self.JpushButton = QtWidgets.QPushButton()
        self.JpushButton.setObjectName("JpushButton")
        self.JpushButton.clicked.connect(self.Writer)
        sizePolicy.setHeightForWidth(self.JpushButton.sizePolicy().hasHeightForWidth())
        self.JpushButton.setSizePolicy(sizePolicy)
        self.gridLayout.addWidget(self.JpushButton, 3, 6, 1, 1)
        
        self.ZpushButton = QtWidgets.QPushButton()
        self.ZpushButton.setObjectName("ZpushButton")
        self.ZpushButton.clicked.connect(self.Writer)
        sizePolicy.setHeightForWidth(self.ZpushButton.sizePolicy().hasHeightForWidth())
        self.ZpushButton.setSizePolicy(sizePolicy)
        self.gridLayout.addWidget(self.ZpushButton, 4, 0, 1, 1)
        
        self.FourpushButton = QtWidgets.QPushButton()
        self.FourpushButton.setObjectName("FourpushButton")
        self.FourpushButton.clicked.connect(self.Writer)
        sizePolicy.setHeightForWidth(self.FourpushButton.sizePolicy().hasHeightForWidth())
        self.FourpushButton.setSizePolicy(sizePolicy)
        self.gridLayout.addWidget(self.FourpushButton, 1, 3, 1, 1)
        
        self.SpushButton = QtWidgets.QPushButton()
        self.SpushButton.setObjectName("SpushButton")
        self.SpushButton.clicked.connect(self.Writer)
        sizePolicy.setHeightForWidth(self.SpushButton.sizePolicy().hasHeightForWidth())
        self.SpushButton.setSizePolicy(sizePolicy)
        self.gridLayout.addWidget(self.SpushButton, 3, 1, 1, 1)
        
        self.QpushButton = QtWidgets.QPushButton()
        self.QpushButton.setObjectName("QpushButton")
        self.QpushButton.clicked.connect(self.Writer)
        sizePolicy.setHeightForWidth(self.QpushButton.sizePolicy().hasHeightForWidth())
        self.QpushButton.setSizePolicy(sizePolicy)
        self.gridLayout.addWidget(self.QpushButton, 2, 0, 1, 1)
        
        self.DpushButton = QtWidgets.QPushButton()
        self.DpushButton.setObjectName("DpushButton")
        self.DpushButton.clicked.connect(self.Writer)
        sizePolicy.setHeightForWidth(self.DpushButton.sizePolicy().hasHeightForWidth())
        self.DpushButton.setSizePolicy(sizePolicy)
        self.gridLayout.addWidget(self.DpushButton, 3, 2, 1, 1)
        
        self.O_pushButton = QtWidgets.QPushButton()
        self.O_pushButton.setObjectName("O_pushButton")
        self.O_pushButton.clicked.connect(self.Writer)
        sizePolicy.setHeightForWidth(self.O_pushButton.sizePolicy().hasHeightForWidth())
        self.O_pushButton.setSizePolicy(sizePolicy)
        self.gridLayout.addWidget(self.O_pushButton, 4, 7, 1, 1)
        
        self.U_pushButton = QtWidgets.QPushButton()
        self.U_pushButton.setObjectName("U_pushButton")
        self.U_pushButton.clicked.connect(self.Writer)
        sizePolicy.setHeightForWidth(self.U_pushButton.sizePolicy().hasHeightForWidth())
        self.U_pushButton.setSizePolicy(sizePolicy)
        self.gridLayout.addWidget(self.U_pushButton, 2, 11, 1, 1)
        
        self.FivepushButton = QtWidgets.QPushButton()
        self.FivepushButton.setObjectName("FivepushButton")
        self.FivepushButton.clicked.connect(self.Writer)
        sizePolicy.setHeightForWidth(self.FivepushButton.sizePolicy().hasHeightForWidth())
        self.FivepushButton.setSizePolicy(sizePolicy)
        self.gridLayout.addWidget(self.FivepushButton, 1, 4, 1, 1)
        
        self.HpushButton = QtWidgets.QPushButton()
        self.HpushButton.setObjectName("HpushButton")
        self.HpushButton.clicked.connect(self.Writer)
        sizePolicy.setHeightForWidth(self.HpushButton.sizePolicy().hasHeightForWidth())
        self.HpushButton.setSizePolicy(sizePolicy)
        self.gridLayout.addWidget(self.HpushButton, 3, 5, 1, 1)
        
        self.Dash_pushButton = QtWidgets.QPushButton()
        self.Dash_pushButton.setObjectName("Dash_pushButton")
        self.Dash_pushButton.clicked.connect(self.Writer)
        sizePolicy.setHeightForWidth(self.Dash_pushButton.sizePolicy().hasHeightForWidth())
        self.Dash_pushButton.setSizePolicy(sizePolicy)
        self.gridLayout.addWidget(self.Dash_pushButton, 3, 11, 1, 1)
        
        self.UpushButton = QtWidgets.QPushButton()
        self.UpushButton.setObjectName("UpushButton")
        self.UpushButton.clicked.connect(self.Writer)
        sizePolicy.setHeightForWidth(self.UpushButton.sizePolicy().hasHeightForWidth())
        self.UpushButton.setSizePolicy(sizePolicy)
        self.gridLayout.addWidget(self.UpushButton, 2, 6, 1, 1)
        
        self.SixpushButton = QtWidgets.QPushButton()
        self.SixpushButton.setObjectName("SixpushButton")
        self.SixpushButton.clicked.connect(self.Writer)
        sizePolicy.setHeightForWidth(self.SixpushButton.sizePolicy().hasHeightForWidth())
        self.SixpushButton.setSizePolicy(sizePolicy)
        self.gridLayout.addWidget(self.SixpushButton, 1, 5, 1, 1)
        
        self.SevenpushButton = QtWidgets.QPushButton()
        self.SevenpushButton.setObjectName("SevenpushButton")
        self.SevenpushButton.clicked.connect(self.Writer)
        sizePolicy.setHeightForWidth(self.SevenpushButton.sizePolicy().hasHeightForWidth())
        self.SevenpushButton.setSizePolicy(sizePolicy)
        self.gridLayout.addWidget(self.SevenpushButton, 1, 6, 1, 1)
        
        self.IpushButton = QtWidgets.QPushButton()
        self.IpushButton.setObjectName("IpushButton")
        self.IpushButton.clicked.connect(self.Writer)
        sizePolicy.setHeightForWidth(self.IpushButton.sizePolicy().hasHeightForWidth())
        self.IpushButton.setSizePolicy(sizePolicy)
        self.gridLayout.addWidget(self.IpushButton, 2, 7, 1, 1)
        
        self.GpushButton = QtWidgets.QPushButton()
        self.GpushButton.setObjectName("GpushButton")
        self.GpushButton.clicked.connect(self.Writer)
        sizePolicy.setHeightForWidth(self.GpushButton.sizePolicy().hasHeightForWidth())
        self.GpushButton.setSizePolicy(sizePolicy)
        self.gridLayout.addWidget(self.GpushButton, 3, 4, 1, 1)
        
        self.TpushButton = QtWidgets.QPushButton()
        self.TpushButton.setObjectName("TpushButton")
        self.TpushButton.clicked.connect(self.Writer)
        sizePolicy.setHeightForWidth(self.TpushButton.sizePolicy().hasHeightForWidth())
        self.TpushButton.setSizePolicy(sizePolicy)
        self.gridLayout.addWidget(self.TpushButton, 2, 4, 1, 1)
        
        self.Shift_pushButton = QtWidgets.QPushButton()
        self.Shift_pushButton.setObjectName("Shift_pushButton")
        self.Shift_pushButton.clicked.connect(self.ShiftPressed)
        sizePolicy.setHeightForWidth(self.Shift_pushButton.sizePolicy().hasHeightForWidth())
        self.Shift_pushButton.setSizePolicy(sizePolicy)
        self.gridLayout.addWidget(self.Shift_pushButton, 5, 1, 1, 1)
        
        self.DeletepushButton = QtWidgets.QPushButton()
        self.DeletepushButton.setObjectName("DeletepushButton")
        self.DeletepushButton.clicked.connect(self.DeleteMeh)
        sizePolicy.setHeightForWidth(self.DeletepushButton.sizePolicy().hasHeightForWidth())
        self.DeletepushButton.setSizePolicy(sizePolicy)
        self.gridLayout.addWidget(self.DeletepushButton, 5, 9, 1, 1)
        
        self.Return_pushButton = QtWidgets.QPushButton()
        self.Return_pushButton.setObjectName("Return_pushButton")
        self.Return_pushButton.clicked.connect(self.ReturnText)
        sizePolicy.setHeightForWidth(self.Return_pushButton.sizePolicy().hasHeightForWidth())
        self.Return_pushButton.setSizePolicy(sizePolicy)
        self.gridLayout.addWidget(self.Return_pushButton, 5, 10, 1, 1)
        
        self.setLayout(self.gridLayout)
        
    def ShiftPressed(self):
        if self.BpushButton.text() == 'B':
            self.LowerCaseLetters()
        else:
            self.UpperCaseLetters()

    def UpperCaseLetters(self):
        
        self.C_pushButton.setText("Ç")
        self.Exclamation_pushButton.setText("!")
        self.YpushButton.setText("Y")
        self.BpushButton.setText("B")
        self.SubDash_pushButton.setText("_")
        self.EightpushButton.setText("8")
        self.EpushButton.setText("E")
        self.Dot_pushButton.setText(".")
        self.OnepushButton.setText("1")
        self.TwopushButton.setText("2")
        self.CpushButton.setText("C")
        self.S_pushButton.setText("Ş")
        self.NinepushButton.setText("9")
        self.RpushButton.setText("R")
        self.G_pushButton.setText("Ğ")
        self.ZeropushButton.setText("0")
        self.XpushButton.setText("X")
        self.VpushButton.setText("V")
        self.I_pushButton.setText("İ")
        self.OpushButton.setText("O")
        self.MpushButton.setText("M")
        self.KpushButton.setText("K")
        self.ThreepushButton.setText("3")
        self.LpushButton.setText("L")
        self.Comma_pushButton.setText(",")
        self.WpushButton.setText("W")
        self.PpushButton.setText("P")
        self.FpushButton.setText("F")
        self.ApushButton.setText("A")
        self.Space_pushButton.setText("Space")
        self.NpushButton.setText("N")
        self.JpushButton.setText("J")
        self.ZpushButton.setText("Z")
        self.FourpushButton.setText("4")
        self.SpushButton.setText("S")
        self.QpushButton.setText("Q")
        self.DpushButton.setText("D")
        self.O_pushButton.setText("Ö")
        self.U_pushButton.setText("Ü")
        self.FivepushButton.setText("5")
        self.HpushButton.setText("H")
        self.Dash_pushButton.setText("-")
        self.UpushButton.setText("U")
        self.SixpushButton.setText("6")
        self.SevenpushButton.setText("7")
        self.IpushButton.setText("I")
        self.GpushButton.setText("G")
        self.TpushButton.setText("T")
        self.Shift_pushButton.setText("Shift")
        self.DeletepushButton.setText("Sil")
        self.Return_pushButton.setText("Tamam")
        
    def LowerCaseLetters(self):
        
        self.C_pushButton.setText("ç")
        self.Exclamation_pushButton.setText("!")
        self.YpushButton.setText("y")
        self.BpushButton.setText("b")
        self.SubDash_pushButton.setText("_")
        self.EightpushButton.setText("8")
        self.EpushButton.setText("e")
        self.Dot_pushButton.setText(".")
        self.OnepushButton.setText("1")
        self.TwopushButton.setText("2")
        self.CpushButton.setText("c")
        self.S_pushButton.setText("ş")
        self.NinepushButton.setText("9")
        self.RpushButton.setText("r")
        self.G_pushButton.setText("ğ")
        self.ZeropushButton.setText("0")
        self.XpushButton.setText("x")
        self.VpushButton.setText("v")
        self.I_pushButton.setText("i")
        self.OpushButton.setText("o")
        self.MpushButton.setText("m")
        self.KpushButton.setText("k")
        self.ThreepushButton.setText("3")
        self.LpushButton.setText("l")
        self.Comma_pushButton.setText(",")
        self.WpushButton.setText("w")
        self.PpushButton.setText("p")
        self.FpushButton.setText("f")
        self.ApushButton.setText("a")
        self.Space_pushButton.setText("Space")
        self.NpushButton.setText("n")
        self.JpushButton.setText("j")
        self.ZpushButton.setText("z")
        self.FourpushButton.setText("4")
        self.SpushButton.setText("s")
        self.QpushButton.setText("q")
        self.DpushButton.setText("d")
        self.O_pushButton.setText("ö")
        self.U_pushButton.setText("ü")
        self.FivepushButton.setText("5")
        self.HpushButton.setText("h")
        self.Dash_pushButton.setText("-")
        self.UpushButton.setText("u")
        self.SixpushButton.setText("6")
        self.SevenpushButton.setText("7")
        self.IpushButton.setText("ı")
        self.GpushButton.setText("g")
        self.TpushButton.setText("t")
        self.Shift_pushButton.setText("Shift")
        self.DeletepushButton.setText("Sil")
        self.Return_pushButton.setText("Tamam")
        
    def Writer(self):
        sender = self.sender()
        if sender.text() == 'Space':
            self.lineEdit.setText(self.lineEdit.text() + ' ')
        else:
            self.lineEdit.setText(self.lineEdit.text() + sender.text())
            
    def DeleteMeh(self):
        self.lineEdit.setText(self.lineEdit.text()[:-1])
        
    def ReturnText(self):
        self.textToReturn.emit(self.lineEdit.text())
        self.close()
